create extension if not exists pgcrypto;

create table if not exists public.customer_share_links (
  id bigint generated by default as identity primary key,
  customer_id bigint not null unique references public.customers(id) on delete cascade,
  share_token text not null unique,
  share_enabled boolean not null default true,
  public_payload jsonb not null default '{}'::jsonb,
  created_by uuid null references auth.users(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_customer_share_links_token on public.customer_share_links (share_token);

alter table public.customer_share_links enable row level security;

drop policy if exists "Admins manage customer share links" on public.customer_share_links;
create policy "Admins manage customer share links"
on public.customer_share_links
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and coalesce(p.is_active, true) = true
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and coalesce(p.is_active, true) = true
  )
);

create or replace function public.customer_share_payload(p_customer_id bigint)
returns jsonb
language sql
security definer
set search_path = public
as $$
  with src as (
    select
      c.id,
      c."ticketId",
      c.name,
      c.phone,
      c.model,
      c.address,
      c.issue,
      c.serial,
      c."replacedPart",
      c.price,
      c."lkItems",
      c.status,
      c."doneDate",
      c."createdAt",
      c.warranty_months,
      c.warranty_start_at,
      c.warranty_expires_at
    from public.customers c
    where c.id = p_customer_id
    limit 1
  )
  select coalesce(
    jsonb_build_object(
      'id', src.id,
      'ticketId', src."ticketId",
      'name', src.name,
      'phone', src.phone,
      'model', src.model,
      'address', case
        when src.address is null or src.address = 'Ca ngoài - không có địa chỉ' then null
        else src.address
      end,
      'issue', src.issue,
      'serial', src.serial,
      'replacedPart', src."replacedPart",
      'price', src.price,
      'lkItems', coalesce(src."lkItems", '[]'::jsonb),
      'status', coalesce(src.status, 0),
      'doneDate', src."doneDate",
      'createdAt', src."createdAt",
      'warranty_label', case
        when src.warranty_months is not null and src.warranty_months > 0 then 'Bao hanh ' || src.warranty_months || ' thang'
        else null
      end,
      'warranty_start_at', src.warranty_start_at,
      'warranty_expires_at', src.warranty_expires_at,
      'warranty_remaining_text', case
        when src.warranty_expires_at is null then null
        when src.warranty_expires_at < timezone('utc', now()) then 'Het bao hanh'
        else 'Con hieu luc'
      end
    ),
    '{}'::jsonb
  )
  from src;
$$;

create or replace function public.set_customer_share_payload()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.public_payload := public.customer_share_payload(new.customer_id);
  new.updated_at := timezone('utc', now());
  if new.share_token is null or length(trim(new.share_token)) < 24 then
    new.share_token := encode(gen_random_bytes(24), 'hex');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_customer_share_payload on public.customer_share_links;
create trigger trg_set_customer_share_payload
before insert or update on public.customer_share_links
for each row
execute function public.set_customer_share_payload();

create or replace function public.touch_customer_share_payload()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.customer_share_links
  set
    public_payload = public.customer_share_payload(new.id),
    updated_at = timezone('utc', now())
  where customer_id = new.id;

  return new;
end;
$$;

drop trigger if exists trg_touch_customer_share_payload on public.customers;
create trigger trg_touch_customer_share_payload
after insert or update of
  "ticketId",
  name,
  phone,
  model,
  address,
  issue,
  serial,
  "replacedPart",
  price,
  "lkItems",
  status,
  "doneDate",
  "createdAt",
  warranty_months,
  warranty_start_at,
  warranty_expires_at
on public.customers
for each row
execute function public.touch_customer_share_payload();

create or replace function public.get_public_customer_share(p_token text)
returns table (
  public_payload jsonb,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    csl.public_payload,
    csl.updated_at
  from public.customer_share_links csl
  where csl.share_enabled = true
    and csl.share_token = trim(p_token)
  limit 1;
$$;

revoke all on public.customer_share_links from anon;
grant select, insert, update, delete on public.customer_share_links to authenticated;
grant usage, select on sequence public.customer_share_links_id_seq to authenticated;

revoke all on public.customers from anon;
revoke all on public.profiles from anon;

revoke all on function public.customer_share_payload(bigint) from public;
revoke all on function public.set_customer_share_payload() from public;
revoke all on function public.touch_customer_share_payload() from public;
revoke all on function public.get_public_customer_share(text) from public;
grant execute on function public.get_public_customer_share(text) to anon, authenticated;

comment on table public.customer_share_links is
'Token-based read-only share links for customer cases. Public users must only access via get_public_customer_share(token).';
